### PR TITLE
Write Opus control header in TSMuxer.

### PR DESCRIPTION
**Pull request by tukez**
Opus does not work with MediaMTX, fix it by writing the control header.

### CODE REVIEW

**Comment by ThibaultBee** [comment]
Hi,
As far as I remember, control header is not mandatory. Do you know why it is mandatory for MediaMTX?

About your dev, MPEG-TS muxer code needs to be rewritten but anyway.
Could you create an object `ControlHeader` that inherits from `ByteBufferWriter` (something similar to https://github.com/ThibaultBee/StreamPack/blob/main/core/src/main/java/io/github/thibaultbee/streampack/internal/utils/av/video/hevc/HEVCDecoderConfigurationRecord.kt)

**Comment by tukez** [comment]
I made some changes, is this what you had in mind?

About the optionality of the control header. Yes the spec indeed says "optional control header" but the following table
image
is not clear about it since one closing brace is missing and possibly the indentation is wrong.

I don't know about MediaMTX, could be that their implementation is just lacking or they interpreted the specification differently.

**Comment by ThibaultBee** [comment]
I create an `OpusControlHeader` data class directly in the TS part (as it seems to be only for TS).
Also, the usage of the frame writer for AAC was because AAC buffer might not be byte-aligned in some cases.

Is there a way I can test on a remote MediaMTX server?

BTW, I also had to rebase your branch because I moved `main`.

**Comment by tukez** [comment]
You could use Docker to setup local MediaMTX with the default config:

`docker run --rm -p 8888:8888 -p 8889:8889 -p 8189:8189/udp -e MTX_WEBRTCADDITIONALHOSTS=192.168.x.x -v bluenviron/mediamtx`

Change the IP in MTX_WEBRTCADDITIONALHOSTS.

Publish to "srt://localhost:8890?streamid=publish:mystream&pkt_size=1316"

View the stream on http://localhost:8889/mystream

**Comment by ThibaultBee** [comment]
Ok, I can run MediaMTX.
But I still don't get audio :( I need to dig again.

**Comment by ThibaultBee** [comment]
Ok, I fixed it. I have tested it with MediaMTX and it works.

The PR is fine like this.

**Comment by ThibaultBee** [comment]
Also, it is worth noticing that they might never be a 2.6.X anymore but only 3.0.X (see dev branch).

**Pull request merged**
