### PR TITLE
Feature/screen recorder

### PR DESCRIPTION
**Pull request by ThibaultBee**

### CODE REVIEW

**Comment by LionMiao** [comment]
I found you delete the branch.

**Comment by ThibaultBee** [comment]
It has been merged into the maser.

**Comment by ThibaultBee** [comment]
You can use 	
```
dependencies {
	        implementation 'com.github.ThibaultBee:StreamPack:master-SNAPSHOT'
	}
```
To test it in your project

**Comment by ThibaultBee** [comment]
By the way, I made also a branch for mediaprojection audio (Android > 10): https://github.com/ThibaultBee/StreamPack/tree/experimental/mediaprojection_audio
I am not sure how to integrate it in the current library yet.

**Comment by LionMiao** [comment]
Thank you very much. You are a nice guy.Where are you from?

**Comment by ThibaultBee** [comment]
France.
If you like the project, star it please :)
Did you test the mediaprojection feature? Did it work? Did you notice something wrong or tricky?

**Pull request merged**
