### PR TITLE
Better auto focus

### PR DESCRIPTION
**Pull request by cdiddy77**
- I found that the demo app did not tap-to-focus correctly, at least, on my Galaxy G22. The code in `addFocusMetering` did not make sense to me. I changed it to align with my understanding, and the demo app tap-to-focus now works. If I am misunderstanding something, please correct me.
- My application has slightly different behavior, where I want to give the user the option of controlling whether tapping causes auto-focus, auto-expose, and whitebalance, all independently. Exposing `getNormalizedPoint` and `startFocusAndMetering` to the outside world enables that.
- I am using jitpack.io to publish my fork for my app, which is in a different repo. In order for jitpack to build successfully, the jitpack.yml is necessary.

### CODE REVIEW

**Comment by ThibaultBee** [comment]
Hi there,
Thanks for the PR. Unfortunately, I can't accept it like this for the following reason:
- don't want the jitpack conifg
- the comment in AutoFitSurfaceView

But this is indeed an interesting PR.

> `I found that the demo app did not tap-to-focus correctly, at least, on my Galaxy G22. The code in addFocusMetering did not make sense to me. I changed it to align with my understanding, and the demo app tap-to-focus now works. If I am misunderstanding something, please correct me.`

Correct me if I am wrong but the change you made for this is only setting `CONTROL_AF_TRIGGER_START` instead of `CONTROL_AF_TRIGGER_CANCEL`? In that case, I need to have a look on this.

> My application has slightly different behavior, where I want to give the user the option of controlling whether tapping causes auto-focus, auto-expose, and whitebalance, all independently. Exposing getNormalizedPoint and startFocusAndMetering to the outside world enables that.
Instead of make `startFocusAndMetering` and `getNormalizedPoint` public, an API to set focus on tap, an API to set exposure on tap and an API to set whitebalance on tap would be a more convenient implementation. Could you confirm?

**Comment by cdiddy77** [comment]
> Hi there, Thanks for the PR. Unfortunately, I can't accept it like this for the following reason:
> 
> * don't want the jitpack conifg
> * the comment in AutoFitSurfaceView
> 
> But this is indeed an interesting PR.
> 
> > `I found that the demo app did not tap-to-focus correctly, at least, on my Galaxy G22. The code in addFocusMetering did not make sense to me. I changed it to align with my understanding, and the demo app tap-to-focus now works. If I am misunderstanding something, please correct me.`
> 
> Correct me if I am wrong but the change you made for this is only setting `CONTROL_AF_TRIGGER_START` instead of `CONTROL_AF_TRIGGER_CANCEL`? In that case, I need to have a look on this.
> 
> > My application has slightly different behavior, where I want to give the user the option of controlling whether tapping causes auto-focus, auto-expose, and whitebalance, all independently. Exposing getNormalizedPoint and startFocusAndMetering to the outside world enables that.
> > Instead of make `startFocusAndMetering` and `getNormalizedPoint` public, an API to set focus on tap, an API to set exposure on tap and an API to set whitebalance on tap would be a more convenient implementation. Could you confirm?

I agree the jitpack thing is not appropriate for this change.

**Comment by ThibaultBee** [comment]
What about the other points?

**Comment by cdiddy77** [comment]
I updated the pr to get rid of the jitpack and the spurious test diff.

What were the other points?

**Comment by ThibaultBee** [comment]
Sorry my question was in the quote.
> Correct me if I am wrong but the change you made for this is only setting CONTROL_AF_TRIGGER_START instead of CONTROL_AF_TRIGGER_CANCEL? In that case, I need to have a look on this.

> Instead of make startFocusAndMetering and getNormalizedPoint public, an API to set focus on tap, an API to set exposure on tap and an API to set whitebalance on tap would be a more convenient implementation. Could you confirm?

**Comment by ThibaultBee** [comment]
I did look at the API. I could add overload the`onTap` API one that get  (afPoints: List<PointF>, aePoints: List<PointF>, awbPoints: List<PointF>)
So you can choose which one you want to set (AE, AWB or Focus). What do you think?

**Comment by cdiddy77** [comment]
I like that.

**Comment by ThibaultBee** [comment]
See https://github.com/ThibaultBee/StreamPack/commit/0d62e557f6cf11a65f1714e098fc15c56c179688 and https://github.com/ThibaultBee/StreamPack/commit/09b313269deceb3d02c61c992f51b12a93300669 instead

**Pull request closed without merging**
